# mini_proj_01_20171541 차영민

## pandas를 이용해 emnist 데이터 받아오기

In [1]:
import sys
import sklearn
import numpy as np
import os
import matplotlib as mpl
import matplotlib.pyplot as plt
import pandas as pd
    
input_file = "emnist-digits-train.csv"
df_train = pd.read_csv(input_file, header = None)

In [2]:
data_train = df_train.to_numpy()
data_train

array([[8, 0, 0, ..., 0, 0, 0],
       [9, 0, 0, ..., 0, 0, 0],
       [6, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

## x_train과 y_train으로 분리하기

In [3]:
x_train = data_train[:,1:]
y_train = data_train[:,0]
x_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [4]:
y_train

array([8, 9, 6, ..., 1, 1, 0], dtype=int64)

## ExtraTreesClassifier사용

https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.ExtraTreesClassifier.html

In [5]:
from sklearn.ensemble import ExtraTreesClassifier
Ex_clf = ExtraTreesClassifier(n_estimators = 500, random_state=42)
Ex_clf.fit(x_train, y_train)

ExtraTreesClassifier(n_estimators=500, random_state=42)

## 10-fold cross-validation 이후 mean값 출력

In [6]:
from sklearn.model_selection import cross_val_score
scoring = cross_val_score(Ex_clf, x_train, y_train, cv=10, scoring="accuracy")
scoring

array([0.98379167, 0.98316667, 0.98375   , 0.98395833, 0.98304167,
       0.98504167, 0.98429167, 0.98483333, 0.982625  , 0.98354167])

In [7]:
np.mean(scoring)

0.9838041666666667

## Mean : 0.9838041666666667